# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
language: ruby
rvm:
  - 2.6.0
branches:
  only:
    - master
install:
  - bundle install
script:
  - set -e
  - bundle exec rake
