// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://badge.fury.io/rb/transcode.svg
:img-hoc: https://hitsofcode.com/github/rdavid/transcode?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/transcode?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-rake: https://github.com/rdavid/transcode/actions/workflows/rake.yml/badge.svg
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/transcode
:url-hoc: https://hitsofcode.com/view/github/rdavid/transcode?branch=master
:url-license: https://github.com/rdavid/transcode/blob/master/LICENSES/0BSD.txt
:url-melton: https://lisamelton.net
:url-rake: https://github.com/rdavid/transcode/actions/workflows/rake.yml
:url-reuse: https://github.com/fsfe/reuse-action
:url-requirements: https://github.com/lisamelton/video_transcoding/blob/master/README.md?ts=2#requirements
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-video: https://github.com/lisamelton/video_transcoding
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Transcode

image:{img-rake}[rake,link={url-rake}]
image:{img-gem}[gem version,link={url-gem}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

Transcode is a command-line tool for transcoding multiple video files.
It builds on {url-melton}[Lisa Melton's] Video Transcoding and applies the
same workflow to each video file in a directory.

== Installation

The tool runs on macOS, GNU/Linux, Windows, and other Unix-like systems.
It is packaged as a Ruby gem and requires Ruby 3.2 or later.
See {url-ruby}[Installing Ruby] if Ruby 3.2+ is not available on your
platform.

Install with:

[,sh]
----
gem install transcode
----

== Updating

Update with:

[,sh]
----
gem update transcode
----

== Requirements

See Video Transcoding's {url-requirements}[requirements] for external
dependencies.

== Usage

[,sh]
----
transcode [options]
  -a, --act      Perform actual encoding.
  -u, --aud aud  Audio stream numbers.
  -d, --dir dir  Source directory to transcode.
  -m, --mp3      Convert files to MP3.
  -o, --out out  Output directory.
  -s, --sca      Scan files in the directory.
  -t, --sub sub  Subtitle stream numbers.
  -i, --tit tit  Specific title number.
  -v, --version  Show version.
  -w, --wid wid  Width of the table.
----

== Example

[,sh]
----
transcode \
  --aud 1,3,1 \
  --dir [source] \
  --out [destination] \
  --sub 2,1,3
----

This command transcodes three files from `[source]` to `[destination]` with
the selected audio and subtitle streams.
Run `--sca` first to inspect available audio and subtitle streams.

== License

`transcode` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
