// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-gem: https://badge.fury.io/rb/transcode.svg
:img-hoc: https://hitsofcode.com/github/rdavid/transcode?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/transcode?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-rake: https://github.com/rdavid/transcode/actions/workflows/rake.yml/badge.svg
:url-cv: http://cv.rabkin.co.il
:url-gem: https://badge.fury.io/rb/transcode
:url-hoc: https://hitsofcode.com/view/github/rdavid/transcode?branch=master
:url-license: https://github.com/rdavid/transcode/blob/master/LICENSES/0BSD.txt
:url-melton: https://lisamelton.net
:url-rake: https://github.com/rdavid/transcode/actions/workflows/rake.yml
:url-reuse: https://github.com/fsfe/reuse-action
:url-requirements: https://github.com/lisamelton/video_transcoding/blob/master/README.md?ts=2#requirements
:url-ruby: https://www.ruby-lang.org/en/documentation/installation
:url-video: https://github.com/lisamelton/video_transcoding
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint

= Transcode

image:{img-rake}[rake,link={url-rake}]
image:{img-gem}[gem version,link={url-gem}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

Transcode is a tool designed for transcoding multiple video files.
It builds upon {url-melton}[Lisa Melton's] Video Transcoding and applies
this technique to each video file within a directory.

== Installation

The tool is designed to work on macOS, GNU/Linux, Windows, Unix-like OS.
It is packaged as a Gem and require Ruby version 3.2 or later.
See {url-ruby}[Installing Ruby] if you don't have the proper version on your
platform.

Use this command to install:

[,sh]
----
gem install transcode
----

== Updating

Use this command to update the package:

[,sh]
----
gem update transcode
----

== Requirements

See Video Transcoding's {url-requirements}[requirements].

== Usage

[,sh]
----
transcode [options]
  -a, --act      Real encoding.
  -s, --sca      Scans files at the directory.
  -m, --mp3      Converts files to mp3.
  -d, --dir dir  Directory to transcode.
  -i, --tit tit  Specific title by number.
  -o, --out out  Directory to output.
  -u, --aud aud  Audio stream numbers.
  -t, --sub sub  Subtitle stream numbers.
  -w, --wid wid  Width of the table.
  -v, --version  Shows version.
----

== Example

[,sh]
----
transcode \
  --aud 1,3,1 \
  --dir [source] \
  --out [destination] \
  --sub 2,1,3
----

It converts three files from source with certain audio and subtitle streams.
Inspect first with `--sca` option to see audio and subtitle streams.

== License

`transcode` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
