# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: rake
'on':
  pull_request:
    paths: &paths
      - '**/*.rb'
      - bin/**
      - Gemfile
      - Gemfile.lock
      - Rakefile
      - '*.gemspec'
      - .github/workflows/rake.yml
  push:
    branches: [master]
    paths: *paths
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  rake:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - macos-15-intel
          - macos-26
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
        ruby:
          - 3.2
          - 3.3
          - 3.4
    name: Rake on ${{ matrix.os }} / Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1.318.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
