# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: rubocop
'on': [pull_request, push]
jobs:
  rubocop:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    env:
      BUNDLE_ONLY: rubocop
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-review  # Default is github-pr-check
          skip_install: true
          use_bundler: true
